## Основная идея / решаемая проблема

В условиях совершенствования сложных технологических инструментов для измерения образовательных результатов, возникает задача глубокого анализа паттернов работы учащихся в цифровой среде с тем, чтобы выявить различия между пользователями с разным уровнем компетентности. Проблема состоит в том, что требуется адаптация и проверка сложных математических моделей и подходов процессного майнинга, успешно используемых в других сферах (банки, телеком).

## Цель и задачи проекта

Цель проекта – отобрать и предложить математическую модель и алгоритмы анализа данных логов о работе учащихся с тем, чтобы можно было выявить паттерны их работы. 
Задачи: 
1. Знакомство с литературой по процессному майнингу и анализу логов
2. Отбор подходящей матмодели
3. Написание скрипта
4. Проверка результатов анализа, их обсуждение.

## Первичный анализ

In [48]:
import pandas as pd

pd.set_option('display.max_columns', 70)

In [49]:
data = pd.read_excel('Спектакль_utf8_2.xlsx', index_col=0) 
data.head(5)

,Username,GGfscore,GGlevel,1TLDCDSILC_log_fulltime,1TLDCDSILC_log_openglasha,1TLDCDSILC_log_exit,1TLDCDSILC_log_firstclick,1TLDCDSILC_log_loginchoose,1TLDCDSILC_log_help,1TLDCDSILC_log_commtypes,1TLDCDSILC_log_commname,1TLDCDSILC_log_commеtheme,1TLDCDSILC_log_commdescription,1TLDCDSILC_log_commfoto,1TLDCDSILC_log_privacy,1TLDCDSILC_log_notion,1TLDCDSILC_log_savepicture,1TLDCDSILC_log_authorN,1TLDCDSILC_log_authortime,1TLDCDSILC_log_savepictureN,1TLDCDSILC_log_picturechoose,1TLDCDSILC_log_picturechooseN,1TLDCDSILC_log_picturechoosedelete,1TLDCDSILC_log_citation,1TLDCDSILC_log_citationcode,1TLDCDSILC_log_mail1,1TLDCDSILC_log_mail2,1TLDCDSILC_log_wall1,1TLDCDSILC_log_private1,1TLDCDSILC_log_private2,1TLDCDSILC_log_wall2,1TLDCDSILC_log_wall2comment3,1TLDCDSILC_log_wall2comment4,1TLDCDSILC_log_wall2comment5,1TLDCDSILC_log_private3,1TLDCDSILC_log_private4,1TLDCDSILC_log_private5,1TLDCDSILC_log_private6,1TLDCDSILC_log_wall3,1TLDCDSILC_log_wall4,1TLDCDSILC_log_copymail,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52
0,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,5667001,0.726641,2,767,0,0,поиск,Pom_Rezh125%,0,Сообщество по интересам,Спектакль «Сон в летнюю ночь»,Постановка спектакля,Уважаемые участники спектакля! Данное сообщест...,Изображение 2,Закрытое,0,4,NaN,NaN,1,4,1,NaN,NaN,NaN,2,1,"Привет! Я думаю, что повезло всем, кто участву...","Не думаю, что стоит об этом кому-то рассказывать.","Не думаю, что стоит заходить на такой сайт","Да ладно тебе, ты думаешь так, другие ребята м...",2,3,1,3,3,1,6,Скачай отсюда: www.videoavi.com,"Ребята, напишите здесь свои комментарии, что у...",soloveym@teatr.ru,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,5667003,0.185260,2,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,5667005,1.258590,3,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5667007,1.478135,3,871,1,0,поиск,Pom_Rezh125%,0,Мероприятие,Наш спектакль «Сон в летнюю ночь»,Постановка спектакля,Всем привет! Это сообщество создано для участн...,Изображение 1,Закрытое,1,"1,5,3,2,4",NaN,NaN,5,2.4,3,5.1,NaN,NaN,2,1,"Привет! Я думаю, что повезло всем, кто участву...","Не думаю, что стоит об этом кому-то рассказывать.","Не думаю, что стоит заходить на такой сайт","Да ладно тебе, ты думаешь так, другие ребята м...",2,3,1,2,3,2,3,Скачай отсюда: www.videoavi.com,"Пусть напишут тебе в личные сообщения, что у н...",Костюмами для нашего спектакля занимается сотр...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,5667009,1.861262,3,631,6,0,почта,Pom_Rezh125%,0,Мероприятие,Спектакль «Сон в летнюю ночь»,Постановка спектакля,Уважаемые участники спектакля! Данное сообщест...,Изображение 3,Закрытое,1,2.1,NaN,NaN,2,2,1,1,d_teatro.diary.org,2,2,1,"Привет! Я думаю, что повезло всем, кто участву...","Не думаю, что стоит об этом кому-то рассказывать.","Не думаю, что стоит заходить на такой сайт","Да ладно тебе, ты думаешь так, другие ребята м...",5,4,1,3,3,3,6,Скачай отсюда: www.videoavi.com,"Пусть напишут тебе в личные сообщения, что у н...",Костюмами для нашего спектакля занимается сотр...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [50]:
data = data.drop(['GGfscore','Username','Unnamed: 42','Unnamed: 43','Unnamed: 44','Unnamed: 45','Unnamed: 46','Unnamed: 47','Unnamed: 48','Unnamed: 49','Unnamed: 50','Unnamed: 51','Unnamed: 52'], axis=1)

In [51]:
data.head(5)

,GGlevel,1TLDCDSILC_log_fulltime,1TLDCDSILC_log_openglasha,1TLDCDSILC_log_exit,1TLDCDSILC_log_firstclick,1TLDCDSILC_log_loginchoose,1TLDCDSILC_log_help,1TLDCDSILC_log_commtypes,1TLDCDSILC_log_commname,1TLDCDSILC_log_commеtheme,1TLDCDSILC_log_commdescription,1TLDCDSILC_log_commfoto,1TLDCDSILC_log_privacy,1TLDCDSILC_log_notion,1TLDCDSILC_log_savepicture,1TLDCDSILC_log_authorN,1TLDCDSILC_log_authortime,1TLDCDSILC_log_savepictureN,1TLDCDSILC_log_picturechoose,1TLDCDSILC_log_picturechooseN,1TLDCDSILC_log_picturechoosedelete,1TLDCDSILC_log_citation,1TLDCDSILC_log_citationcode,1TLDCDSILC_log_mail1,1TLDCDSILC_log_mail2,1TLDCDSILC_log_wall1,1TLDCDSILC_log_private1,1TLDCDSILC_log_private2,1TLDCDSILC_log_wall2,1TLDCDSILC_log_wall2comment3,1TLDCDSILC_log_wall2comment4,1TLDCDSILC_log_wall2comment5,1TLDCDSILC_log_private3,1TLDCDSILC_log_private4,1TLDCDSILC_log_private5,1TLDCDSILC_log_private6,1TLDCDSILC_log_wall3,1TLDCDSILC_log_wall4,1TLDCDSILC_log_copymail
0,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,2,767,0,0,поиск,Pom_Rezh125%,0,Сообщество по интересам,Спектакль «Сон в летнюю ночь»,Постановка спектакля,Уважаемые участники спектакля! Данное сообщест...,Изображение 2,Закрытое,0,4,NaN,NaN,1,4,1,NaN,NaN,NaN,2,1,"Привет! Я думаю, что повезло всем, кто участву...","Не думаю, что стоит об этом кому-то рассказывать.","Не думаю, что стоит заходить на такой сайт","Да ладно тебе, ты думаешь так, другие ребята м...",2,3,1,3,3,1,6,Скачай отсюда: www.videoavi.com,"Ребята, напишите здесь свои комментарии, что у...",soloveym@teatr.ru
2,2,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined
3,3,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined
4,3,871,1,0,поиск,Pom_Rezh125%,0,Мероприятие,Наш спектакль «Сон в летнюю ночь»,Постановка спектакля,Всем привет! Это сообщество создано для участн...,Изображение 1,Закрытое,1,"1,5,3,2,4",NaN,NaN,5,2.4,3,5.1,NaN,NaN,2,1,"Привет! Я думаю, что повезло всем, кто участву...","Не думаю, что стоит об этом кому-то рассказывать.","Не думаю, что стоит заходить на такой сайт","Да ладно тебе, ты думаешь так, другие ребята м...",2,3,1,2,3,2,3,Скачай отсюда: www.videoavi.com,"Пусть напишут тебе в личные сообщения, что у н...",Костюмами для нашего спектакля занимается сотр...
5,3,631,6,0,почта,Pom_Rezh125%,0,Мероприятие,Спектакль «Сон в летнюю ночь»,Постановка спектакля,Уважаемые участники спектакля! Данное сообщест...,Изображение 3,Закрытое,1,2.1,NaN,NaN,2,2,1,1,d_teatro.diary.org,2,2,1,"Привет! Я думаю, что повезло всем, кто участву...","Не думаю, что стоит об этом кому-то рассказывать.","Не думаю, что стоит заходить на такой сайт","Да ладно тебе, ты думаешь так, другие ребята м...",5,4,1,3,3,3,6,Скачай отсюда: www.videoavi.com,"Пусть напишут тебе в личные сообщения, что у н...",Костюмами для нашего спектакля занимается сотр...

In [52]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2796 entries, 1 to 2796
Data columns (total 39 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   GGlevel                             2796 non-null   int64
 1   1TLDCDSILC_log_fulltime             2759 non-null   object
 2   1TLDCDSILC_log_openglasha           2759 non-null   object
 3   1TLDCDSILC_log_exit                 2747 non-null   object
 4   1TLDCDSILC_log_firstclick           2046 non-null   object
 5   1TLDCDSILC_log_loginchoose          2751 non-null   object
 6   1TLDCDSILC_log_help                 2759 non-null   object
 7   1TLDCDSILC_log_commtypes            2728 non-null   object
 8   1TLDCDSILC_log_commname             2728 non-null   object
 9   1TLDCDSILC_log_commеtheme           2728 non-null   object
 10  1TLDCDSILC_log_commdescription      2725 non-null   object
 11  1TLDCDSILC_log_commfoto             2725 non-null   object
 12  1TLDCDSILC_log_privacy              2725 non-null   object
 13  1TLDCDSILC_log_notion               2759 non-null   object
 14  1TLDCDSILC_log_savepicture          2704 non-null   object
 15  1TLDCDSILC_log_authorN              824 non-null    object
 16  1TLDCDSILC_log_authortime           824 non-null    object
 17  1TLDCDSILC_log_savepictureN         2704 non-null   object
 18  1TLDCDSILC_log_picturechoose        2689 non-null   object
 19  1TLDCDSILC_log_picturechooseN       2690 non-null   object
 20  1TLDCDSILC_log_picturechoosedelete  773 non-null    object
 21  1TLDCDSILC_log_citation             1629 non-null   object
 22  1TLDCDSILC_log_citationcode         1631 non-null   object
 23  1TLDCDSILC_log_mail1                2675 non-null   object
 24  1TLDCDSILC_log_mail2                2672 non-null   object
 25  1TLDCDSILC_log_wall1                2659 non-null   object
 26  1TLDCDSILC_log_private1             2330 non-null   object
 27  1TLDCDSILC_log_private2             2652 non-null   object
 28  1TLDCDSILC_log_wall2                2640 non-null   object
 29  1TLDCDSILC_log_wall2comment3        2644 non-null   object
 30  1TLDCDSILC_log_wall2comment4        2643 non-null   object
 31  1TLDCDSILC_log_wall2comment5        2642 non-null   object
 32  1TLDCDSILC_log_private3             2619 non-null   object
 33  1TLDCDSILC_log_private4             2616 non-null   object
 34  1TLDCDSILC_log_private5             2600 non-null   object
 35  1TLDCDSILC_log_private6             2585 non-null   object
 36  1TLDCDSILC_log_wall3                2604 non-null   object
 37  1TLDCDSILC_log_wall4                2592 non-null   object
 38  1TLDCDSILC_log_copymail             2505 non-null   object
dtypes: int64(1), object(38)
memory usage: 873.8+ KB

## Предобработка

#### Удаление дубликатов

In [53]:
# проверим на дубликаты исходные данные
data.duplicated().sum()

np.int64(391)

In [54]:
data = data.drop_duplicates().reset_index(drop=True)

In [55]:
data.duplicated().sum()

np.int64(0)

In [56]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2405 entries, 0 to 2404
Data columns (total 39 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   GGlevel                             2405 non-null   int64
 1   1TLDCDSILC_log_fulltime             2401 non-null   object
 2   1TLDCDSILC_log_openglasha           2401 non-null   object
 3   1TLDCDSILC_log_exit                 2394 non-null   object
 4   1TLDCDSILC_log_firstclick           1693 non-null   object
 5   1TLDCDSILC_log_loginchoose          2398 non-null   object
 6   1TLDCDSILC_log_help                 2401 non-null   object
 7   1TLDCDSILC_log_commtypes            2376 non-null   object
 8   1TLDCDSILC_log_commname             2376 non-null   object
 9   1TLDCDSILC_log_commеtheme           2376 non-null   object
 10  1TLDCDSILC_log_commdescription      2373 non-null   object
 11  1TLDCDSILC_log_commfoto             2373 non-null   object
 12  1TLDCDSILC_log_privacy              2373 non-null   object
 13  1TLDCDSILC_log_notion               2401 non-null   object
 14  1TLDCDSILC_log_savepicture          2352 non-null   object
 15  1TLDCDSILC_log_authorN              472 non-null    object
 16  1TLDCDSILC_log_authortime           472 non-null    object
 17  1TLDCDSILC_log_savepictureN         2352 non-null   object
 18  1TLDCDSILC_log_picturechoose        2337 non-null   object
 19  1TLDCDSILC_log_picturechooseN       2338 non-null   object
 20  1TLDCDSILC_log_picturechoosedelete  421 non-null    object
 21  1TLDCDSILC_log_citation             1277 non-null   object
 22  1TLDCDSILC_log_citationcode         1279 non-null   object
 23  1TLDCDSILC_log_mail1                2323 non-null   object
 24  1TLDCDSILC_log_mail2                2320 non-null   object
 25  1TLDCDSILC_log_wall1                2307 non-null   object
 26  1TLDCDSILC_log_private1             1978 non-null   object
 27  1TLDCDSILC_log_private2             2300 non-null   object
 28  1TLDCDSILC_log_wall2                2288 non-null   object
 29  1TLDCDSILC_log_wall2comment3        2292 non-null   object
 30  1TLDCDSILC_log_wall2comment4        2291 non-null   object
 31  1TLDCDSILC_log_wall2comment5        2290 non-null   object
 32  1TLDCDSILC_log_private3             2267 non-null   object
 33  1TLDCDSILC_log_private4             2264 non-null   object
 34  1TLDCDSILC_log_private5             2248 non-null   object
 35  1TLDCDSILC_log_private6             2233 non-null   object
 36  1TLDCDSILC_log_wall3                2252 non-null   object
 37  1TLDCDSILC_log_wall4                2240 non-null   object
 38  1TLDCDSILC_log_copymail             2153 non-null   object
dtypes: int64(1), object(38)
memory usage: 732.9+ KB

#### Замена названий колонок

In [62]:
data = data.rename(
    columns={
        '1TLDCDSILC_log_fulltime': 'fulltime',
        '1TLDCDSILC_log_openglasha':'openglasha',
        '1TLDCDSILC_log_exit':'exit',
        '1TLDCDSILC_log_firstclick':'firstclick',
        '1TLDCDSILC_log_loginchoose':'loginchoose',
        '1TLDCDSILC_log_help':'help',
        '1TLDCDSILC_log_commtypes':'commtypes',
        '1TLDCDSILC_log_commname':'commname',
        '1TLDCDSILC_log_commеtheme':'commеtheme',
        '1TLDCDSILC_log_commdescription':'commdescription',
        '1TLDCDSILC_log_commfoto':'commfoto',
        '1TLDCDSILC_log_privacy':'privacy',
        '1TLDCDSILC_log_notion':'notion',
        '1TLDCDSILC_log_savepicture':'savepicture',
        '1TLDCDSILC_log_authorN':'authorN',
        '1TLDCDSILC_log_authortime':'authortime',
        '1TLDCDSILC_log_savepictureN':'savepictureN',
        '1TLDCDSILC_log_picturechoose':'picturechoose',
        '1TLDCDSILC_log_picturechooseN':'picturechooseN',
        '1TLDCDSILC_log_picturechoosedelete':'picturechoosedelete',
        '1TLDCDSILC_log_citation':'citation',
        '1TLDCDSILC_log_citationcode':'citationcode',
        '1TLDCDSILC_log_mail1':'mail1',
        '1TLDCDSILC_log_mail2':'mail2',
        '1TLDCDSILC_log_wall1':'wall1',
        '1TLDCDSILC_log_private1':'private1',
        '1TLDCDSILC_log_private2':'private2',
        '1TLDCDSILC_log_wall2':'wall2',
        '1TLDCDSILC_log_wall2comment3':'wall2comment3',
        '1TLDCDSILC_log_wall2comment4':'wall2comment4',
        '1TLDCDSILC_log_wall2comment5':'wall2comment5',
        '1TLDCDSILC_log_private3':'private3',
        '1TLDCDSILC_log_private4':'private4',
        '1TLDCDSILC_log_private5':'private5',
        '1TLDCDSILC_log_private6':'private6',
        '1TLDCDSILC_log_wall3':'wall3',
        '1TLDCDSILC_log_wall4':'wall4',
        '1TLDCDSILC_log_copymail':'copymail'
    }
)

In [63]:
data.head(5)

,GGlevel,fulltime,openglasha,exit,firstclick,loginchoose,help,commtypes,commname,commеtheme,commdescription,commfoto,privacy,notion,savepicture,authorN,authortime,savepictureN,picturechoose,picturechooseN,picturechoosedelete,citation,citationcode,mail1,mail2,wall1,private1,private2,wall2,wall2comment3,wall2comment4,wall2comment5,private3,private4,private5,private6,wall3,wall4,copymail
0,2,767,0,0,поиск,Pom_Rezh125%,0,Сообщество по интересам,Спектакль «Сон в летнюю ночь»,Постановка спектакля,Уважаемые участники спектакля! Данное сообщест...,Изображение 2,Закрытое,0,4,NaN,NaN,1,4,1,NaN,NaN,NaN,2,1,"Привет! Я думаю, что повезло всем, кто участву...","Не думаю, что стоит об этом кому-то рассказывать.","Не думаю, что стоит заходить на такой сайт","Да ладно тебе, ты думаешь так, другие ребята м...",2,3,1,3,3,1,6,Скачай отсюда: www.videoavi.com,"Ребята, напишите здесь свои комментарии, что у...",soloveym@teatr.ru
1,2,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined
2,3,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined
3,3,871,1,0,поиск,Pom_Rezh125%,0,Мероприятие,Наш спектакль «Сон в летнюю ночь»,Постановка спектакля,Всем привет! Это сообщество создано для участн...,Изображение 1,Закрытое,1,"1,5,3,2,4",NaN,NaN,5,2.4,3,5.1,NaN,NaN,2,1,"Привет! Я думаю, что повезло всем, кто участву...","Не думаю, что стоит об этом кому-то рассказывать.","Не думаю, что стоит заходить на такой сайт","Да ладно тебе, ты думаешь так, другие ребята м...",2,3,1,2,3,2,3,Скачай отсюда: www.videoavi.com,"Пусть напишут тебе в личные сообщения, что у н...",Костюмами для нашего спектакля занимается сотр...
4,3,631,6,0,почта,Pom_Rezh125%,0,Мероприятие,Спектакль «Сон в летнюю ночь»,Постановка спектакля,Уважаемые участники спектакля! Данное сообщест...,Изображение 3,Закрытое,1,2.1,NaN,NaN,2,2,1,1,d_teatro.diary.org,2,2,1,"Привет! Я думаю, что повезло всем, кто участву...","Не думаю, что стоит об этом кому-то рассказывать.","Не думаю, что стоит заходить на такой сайт","Да ладно тебе, ты думаешь так, другие ребята м...",5,4,1,3,3,3,6,Скачай отсюда: www.videoavi.com,"Пусть напишут тебе в личные сообщения, что у н...",Костюмами для нашего спектакля занимается сотр...

**Расшифровка столбцов**
- **GGlevel** - уровень цг	
- **fulltime** - Суммарное время на выполнении задания
- **openglasha** - Фиксируется количество раз, которое Глаша вызвана самостоятельно респондентом в течение всего выполнения задания (самостоятельные клики на иконку ассистента) 
- **exit** - Фиксируется нажатие на кнопку “Следующее задание” 
- **firstclick** - Фиксируется название вкладки (после открытой по дефолту), по которой сделан первый клик, т.е. вкладка, которая открыта следующей после соцсети: почта, поиск 
- **loginchoose** - Фиксируется какой логин выбрал респондент из трех предложенных в выпадающем списке 
- **help** - Обращения к справке
- **commtypes** - Выбранный тип сообщества, фиксируется текстом, один из возможных: Бизнес, Тематическое сообщество, Бренд или организация, Сообщество по интересам, Публичная страница, Мероприятие 
- **commname** - Выбранное название сообщества, фиксируется текстом, одно из возможных 
- **commеtheme** - Выбранная тематика сообщества, фиксируется текстом 
- **commdescription** - Выбранное описание для сообщества
- **commfot** - Выбранное фото для сообщества(номер/ название)
- **privacу** - Выбранная настройка закрытое/открытое/частное
- **notion** - Фиксируется количество раз, сколько появлялось выделение красным в процессе заполнения данных о сообществе (описание, обложка, настройка закрытое/ открытое/ частное)
- **savepicture** - Фиксируется количество сохранённых изображений (шт, если не сохранил ни одной, то NA)
- **authorN** - Фиксируется суммарное число кликов-переходов по ссылке "Что такое авторское право?" (из-под любого изображения, ДО момента публикации запись, то есть всё то, что он тыкает ПОСЛЕ публикации, не учитывается). (шт int, если не переходил, то NA)
- **authortime** - Фиксируется время чтения поп-апа “Что такое авторское право” (суммарное, при многократном включении поп-апа и до конца модуля 7) (сек, если не переходил, то NA)
- **savepictureN** - Фиксируется количество сохранённых изображений (шт, если не сохранил ни одной, то NA)
- **picturechoose** - Фиксируется выбранная для размещения картинка (1,5,7) если ничего не опубликовал, то NA
- **picturechooseN** - Фиксируется количество опубликованных изображений (шт, если не сохранил ни одной, то NA)
- **picturechoosedelete** - фиксируется, какие фотографии были добавлены к посту и удалены (1,7), записывается в арифметическом порядке, (если не использовалось удаление, то NA)
- **citatio** - Фиксируется вставленный текст к фотоn
- **citationcode** - Фиксируется код вставленных блоков текста (блоки текста закодированы в соответствии со своими изображениями 1,5,7 (хотя бы один блок текста вставлен = 3) если ничего не добавил, то NA
- **mail1** - Фиксируется выбранный ответ после письма учителя 1 (1,2,3)
- **mail2** - Фиксируется выбранный ответ после письма учителя 2 (1,2,3)
- **wall1** - Фиксируется выбранный ответ на 1 сообщение на стене
- **private1** - Фиксируется выбранный ответ на 1 сообщение л/с
- **private2** - Фиксируется выбранный ответ на 2 сообщение л/с
- **wall2** - Фиксируется выбранный ответ на 2 сообщение на стене
- **wall2comment3** - выбранный ответ к комментарию 3
- **wall2comment4** - выбранный ответ к комментарию 4
- **wall2comment5** - выбранный ответ к комментарию 5
- **private3** - Выбранный ответ в 3 л/с
- **private4** - Выбранный ответ в 4 л/с 
- **private5** - Выбранный ответ в  л/с 5
- **private6** - Выбранный ответ в  6 сообщении в л/с
- **wall3** - Выбранный ответ в  3 сообщении на стене (какая выбрана ссылка)
- **wall4** - Выбранный ответ в  4 сообщении на стене
- **copymail** - Копирует текст или контакты